spring:
  security:
    saml2:
      relyingparty:
        registration:
          infinity:
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: classpath:metadata.xml

  h2:
    console:
      enabled: 'true'
      path: /h2-ui
  datasource:
    username: sa
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  ssl:
    key-store-password: SunGard1!
    key-store-type: PKCS12
    key-alias: baeldung
    key-store: classpath:security/keystore/baeldung.p12
  error:
    whitelabel:
      enabled: 'false'
  port: '9091'
security:
  require-ssl: 'true'
trust:
  store:
    nodeValue: classpath:security/keystore/baeldung.p12
    password: SunGard1!

demo:
  app:
    jwtExpirationMs: '86400000'
    jwtCookieName: bezkoder
    jwtSecret: bezKoderSecretKey


